/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getMyFSMAccess().getAlternatives_5(), "rule__MyFSM__Alternatives_5");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getMyFSMAccess().getGroup(), "rule__MyFSM__Group__0");
			builder.put(grammarAccess.getMyFSMAccess().getGroup_5_0(), "rule__MyFSM__Group_5_0__0");
			builder.put(grammarAccess.getMyFSMAccess().getGroup_5_0_2(), "rule__MyFSM__Group_5_0_2__0");
			builder.put(grammarAccess.getMyFSMAccess().getGroup_5_1(), "rule__MyFSM__Group_5_1__0");
			builder.put(grammarAccess.getMyFSMAccess().getGroup_5_1_2(), "rule__MyFSM__Group_5_1_2__0");
			builder.put(grammarAccess.getMyFSMAccess().getGroup_5_2(), "rule__MyFSM__Group_5_2__0");
			builder.put(grammarAccess.getMyFSMAccess().getGroup_5_2_2(), "rule__MyFSM__Group_5_2_2__0");
			builder.put(grammarAccess.getStateAccess().getGroup(), "rule__State__Group__0");
			builder.put(grammarAccess.getFinalStateAccess().getGroup(), "rule__FinalState__Group__0");
			builder.put(grammarAccess.getInitialStateAccess().getGroup(), "rule__InitialState__Group__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup(), "rule__Transition__Group__0");
			builder.put(grammarAccess.getMyFSMAccess().getNameAssignment_2(), "rule__MyFSM__NameAssignment_2");
			builder.put(grammarAccess.getMyFSMAccess().getStateAssignment_4_0(), "rule__MyFSM__StateAssignment_4_0");
			builder.put(grammarAccess.getMyFSMAccess().getInitialstateAssignment_4_1(), "rule__MyFSM__InitialstateAssignment_4_1");
			builder.put(grammarAccess.getMyFSMAccess().getStateAssignment_5_0_1(), "rule__MyFSM__StateAssignment_5_0_1");
			builder.put(grammarAccess.getMyFSMAccess().getStateAssignment_5_0_2_1(), "rule__MyFSM__StateAssignment_5_0_2_1");
			builder.put(grammarAccess.getMyFSMAccess().getTrAssignment_5_1_1(), "rule__MyFSM__TrAssignment_5_1_1");
			builder.put(grammarAccess.getMyFSMAccess().getTrAssignment_5_1_2_1(), "rule__MyFSM__TrAssignment_5_1_2_1");
			builder.put(grammarAccess.getMyFSMAccess().getStateAssignment_5_2_1(), "rule__MyFSM__StateAssignment_5_2_1");
			builder.put(grammarAccess.getMyFSMAccess().getStateAssignment_5_2_2_1(), "rule__MyFSM__StateAssignment_5_2_2_1");
			builder.put(grammarAccess.getStateAccess().getNameAssignment_1(), "rule__State__NameAssignment_1");
			builder.put(grammarAccess.getFinalStateAccess().getNameAssignment_1(), "rule__FinalState__NameAssignment_1");
			builder.put(grammarAccess.getInitialStateAccess().getNameAssignment_1(), "rule__InitialState__NameAssignment_1");
			builder.put(grammarAccess.getTransitionAccess().getNameAssignment_1(), "rule__Transition__NameAssignment_1");
			builder.put(grammarAccess.getTransitionAccess().getFromAssignment_3(), "rule__Transition__FromAssignment_3");
			builder.put(grammarAccess.getTransitionAccess().getToAssignment_5(), "rule__Transition__ToAssignment_5");
			builder.put(grammarAccess.getMyFSMAccess().getUnorderedGroup_4(), "rule__MyFSM__UnorderedGroup_4");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
